### ISSUE TITLE
Shaman/Stormkeeper

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#1]
**Description:**

Stormkeeper (191634) doesnt work correctly

**Current behaviour:**
Casting Stormkeeper allows you to instant cast (chain lightning and lightning bolt ) while buff last

**Expected behaviour:**
Stormkeeper allows you to instant cast (chain lightning and lightning bolt ) only 2 times

**Steps to reproduce the problem:**

1. Cast Stormkeeper (191634)
2. Cast spells
3. Step 3

**Branch(es):**

Dont know

**TC rev. hash/commit:** 

Dont know

**Operating system:**  Windows 10

**Comment by searum** [comment]
Fixed for next release
