### ISSUE TITLE
Paladin/Blessing of Wisdom

### ISSUE THREAD

**Issue by Walfolie** [xXBentRealityXx/Greymane-Bugtracker#107]
**Description:**

Greater Blessing of Wisdom should restore 1% Health and 1% Mana every 10 seconds but instead it restores it every second.

**Current behaviour:**

Greater Blessing of Wisdom restores 1% Health and 1% Mana every second.

**Expected behaviour:**

Greater Blessing of Wisdom should restore 1% Health and 1% Mana every 10 seconds.

**Steps to reproduce the problem:**

1. Cast spell.

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** Windows 10

**Comment by xXBentRealityXx** [comment]
As weird as this one is, it is actually supposed to heal you 1% every 2 seconds according to wowhead and the db2 files
