### ISSUE TITLE
Shaman/Talent/Static Charge

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#11]
**Description:**
[Static Charge](https://www.wowhead.com/spell=265046/static-charge) doesnt work

**Current behaviour:**
1.Static Charge doesnt reduce cooldown of Capacitor Totem

**Expected behaviour:**
1.Static Charge should reduce cooldown of Capacitor Totem by 5 sec for each enemy it stuns, up to a maximum reduction of 20 sec.

**Steps to reproduce the problem:**
1. Pick Static Charge talent(265046)
2. Stun few NPC with Capacitor Totem

**Branch(es):**
Master

**TC rev. hash/commit:** 
Do not worry about this.

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
