### ISSUE TITLE
Monk / Rushing Jade wind

### ISSUE THREAD

**Issue by Burkinc** [xXBentRealityXx/Greymane-Bugtracker#110]
Description:
Rushing Jade wind isnt working windwalker https://www.wowhead.com/spell=261715/rushing-jade-wind

Current behaviour:
1.Rushing Jade wind isnt working it takes too long there is no colldown when off

Expected behaviour:
1, it takes too long there is no colldown when off

Steps to reproduce the problem:

1, Learn windwalker and cast spell Rushing Jade wind 

Branch(es):

Master

TC rev. hash/commit:

Do not worry about this.

Operating system: I tested it on Windows 10 (64bit) and on the Windows 7 (64bit)

**Comment by xXBentRealityXx** [comment]
Rushing Jade Wind is only available when in the Brewmaster spec.
