### ISSUE TITLE
Shaman/Talent/Storm Elemental

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#12]
**Description:**
[Storm Elemental](https://www.wowhead.com/spell=192249/storm-elemental) isn't working at all

**Current behaviour:**
1. Storm Elemental doesn't spawn Greater Storm Elemental
2.Doesnt give you cast time reduction on Lightning Bolt and Chain Lightning

**Expected behaviour:**
1.Storm Elemental should spawn Greater Storm Elemental which should cast gust of winds and should last 30 sec
2.While the Storm Elemental is active, each time you cast Lightning Bolt or Chain Lightning, the cast time of Lightning Bolt and Chain Lightning is reduced by 3%, stacking up to 20 times.

**Steps to reproduce the problem:**
1. Pick Storm Elemental talent (192249)  
2. Use it

**Branch(es):**
Master

**TC rev. hash/commit:** 
Do not worry about this.

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
