### ISSUE TITLE
Shaman/Talent/Liquid Magma Totem

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#13]
**Description:**
[Liquid Magma Totem](https://www.wowhead.com/spell=192222/liquid-magma-totem) doesn't work at all

**Current behaviour:**
1.Spell spawn a totem which doesn't attack .

**Expected behaviour:**
1.Summons a totem at the target location for 15 sec that hurls liquid magma at a random nearby target every 1 sec, dealing [(15% of Spell power) * (1.02)] Fire damage to all enemies within 8 yards.

**Steps to reproduce the problem:**
1. Pick Liquid Magma Totem talent(192222)
2. Use it near target

**Branch(es):**
Master

**TC rev. hash/commit:** 
Do not worry about this.

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
