### ISSUE TITLE
Shaman/Talent/Nature's Guardian

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#14]
**Description:**
[Nature's Guardian](https://www.wowhead.com/spell=30884/natures-guardian) is half working

**Current behaviour:**
1.Nature's Guardian proc every 45 sec 

**Expected behaviour:**
1.Nature's Guardian should proc only when you drop bellow 30 % of health

**Steps to reproduce the problem:**
1. Pick Nature's Guardian talent(30884) 
2. Let some NPC attack you

**Branch(es):**
Master

**TC rev. hash/commit:** 
Do not worry about this.

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
