### ISSUE TITLE
Shaman/Talent/Primal Elementalist

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#15]
**Description:**
[Primal Elementalist](https://www.wowhead.com/spell=117013/primal-elementalist) isn't working at all

**Current behaviour:**
1.Primal Elementalist doesnt change appearance of Fire and Earth elementals
2.Primal Elementalist doesnt give you ability to control your elementals

**Expected behaviour:**
1.Your Earth, Fire, and Storm Elementals are drawn from primal elementals 80% more powerful than regular elementals, with additional abilities, and you gain direct control over them.

**Steps to reproduce the problem:**

1. Pick Primal Elementalist talent (117013)
2. Use your elementals

**Branch(es):**
Master

**TC rev. hash/commit:** 

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
