### ISSUE TITLE
Shaman/Talent/Ascendance

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#16]
**Description:**
[Ascendance](https://www.wowhead.com/spell=114050/ascendance) is half working

**Current behaviour:**
1.Ascendance doesn't increase Lava Burst damage

**Expected behaviour:**
1.Transform into a Flame Ascendant for 15 sec, replacing Chain Lightning with Lava Beam, removing the cooldown on Lava Burst, **and increasing the damage of Lava Burst by an amount equal to your critical strike chance.**

**Steps to reproduce the problem:**
1. Pick Ascendance talent(114050)
2. Use it

**Branch(es):**
Master

**TC rev. hash/commit:** 

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
