### ISSUE TITLE
Shaman/Healing Tide Totem

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#17]
**Description:**
[Healing Tide Totem](https://www.wowhead.com/spell=108280/healing-tide-totem) isn't working

**Current behaviour:**
1.Healing Tide Totem doesn't heal

**Expected behaviour:**
1.Summons a totem at your feet for 10 sec, which pulses every 2 sec, healing all party or raid members within 40 yards for (24% of Spell power).

**Steps to reproduce the problem:**
1.Use Healing Tide Totem 

**Branch(es):**
Master

**TC rev. hash/commit:** 

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
