### ISSUE TITLE
Shaman/Talent/Undulation

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#18]
**Description:**
[Undulation](https://www.wowhead.com/spell=200071/undulation) isn't working

**Current behaviour:**
1.Undulation doesnt give increased healing every third Healing Wave or Healing Surge

**Expected behaviour:**
1.Every third Healing Wave or Healing Surge heals for an additional 50%.

**Steps to reproduce the problem:**
1. Pick Undulation talent(200071)
2. Cast Healing Wave

**Branch(es):**
Master

**TC rev. hash/commit:** 

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
