### ISSUE TITLE
Shaman/Talent/Deluge

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#19]
**Description:**
[Deluge](https://www.wowhead.com/spell=200076/deluge) isn't working

**Current behaviour:**
1.Deluge doesn't increase Chain Heal healing if you are affected by Healing Rain or Riptide

**Expected behaviour:**
1.Chain Heal heals for an additional 20% on targets within your Healing Rain or affected by your Riptide.

**Steps to reproduce the problem:**

1. Pick Deluge talent(200076) 
2. Cast Healing Rain or Riptide on yourself 
3. Cast Chain Heal on yourself

**Branch(es):**
Master

**TC rev. hash/commit:** 

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
