### ISSUE TITLE
Shaman/Elemental Overload

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#2]
**Description:**
Mastery:Elemental Overload(168534) isnt working at all

**Current behaviour:**
Chain lightning and lightning bolt dont proc Elemental Overload at all

**Expected behaviour:**
Lava Burst,Chain Lightning,Lightning Bolt,Elemental Blast should proc Elemental Overload

**Steps to reproduce the problem:**

1. Cast above named spells on target  
2. Watch for the proc
3. Step 3

**Branch(es):**

Dont know

**TC rev. hash/commit:** 

Dont know
**Operating system:** Windows 10

**Comment by searum** [comment]
Fix
