### ISSUE TITLE
Shaman/Talent/Flash Flood

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#28]
**Description:**
[Flash Flood](https://www.wowhead.com/spell=280614/flash-flood) doesnt work

**Current behaviour:**
1.Flash Flood doesnt proc after consuming [Tidal Waves](https://www.wowhead.com/spell=51564/tidal-waves)

**Expected behaviour:**
1.When you consume Tidal Waves, the cast time of your next heal is reduced by 20% if you have this talent

**Steps to reproduce the problem:**

1. Pick Flash Flood talent(280614)
2. Consume Tidal Wave 
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
