### ISSUE TITLE
Shaman/Talent/Exposed Elements

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#3]
**Description:**
Exposed Elements(269808) doesnt work correctly

**Current behaviour:**
1.Each damaging spell gives a debuff on enemy giving you Exposed Elements 
2.Exposed Elements isnt removed when you cast Lightning Bolt on target.

**Expected behaviour:**
Only Earth Shock should give you the Debuff,not every damaging spell and Debuff should be removed from target after next Lightning Bolt

**Steps to reproduce the problem:**

1. Pick Exposed Elements talent
2. Cast Lightning Bolt
3. Cast Earth Shock

**Branch(es):**

Master

**TC rev. hash/commit:** 
Dont know

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
