### ISSUE TITLE
Shaman/Flametongue

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#30]
**Description:**
[Flametongue](https://www.wowhead.com/spell=193796/flametongue) do more damage then it should

**Current behaviour:**
1.Flametongue tooltip say "Each weapon attack deal up to 397 damage.My attacks are doing 1000+ damage without crits
2.Initial damage is ok

**Expected behaviour:**
1.Scorches your target, dealing (14.742% of Attack power) Fire damage, and enhances your weapons with fire for 16 sec, causing each weapon attack to deal up to (0 * Attack power) Fire damage.

**Steps to reproduce the problem:**

1. Cast flametongue on target 

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
