### ISSUE TITLE
Shaman/Lava Lash

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#31]
**Description:**
[Lava Lash ](https://www.wowhead.com/spell=60103/lava-lash) is doing more damage then it should

**Current behaviour:**
1.Lava Lash is doing 10 195 damage non crit and the tooltip says it should do 5099 damage per hit

**Expected behaviour:**
1.Charges your off-hand weapon with lava and burns your target, dealing (108% of Attack power) Fire damage.

**Steps to reproduce the problem:**

1. Cast Lava Lash on target

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
