### ISSUE TITLE
Shaman/Crash Lightning

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#32]
**Description:**
[Crash Lightning](https://www.wowhead.com/spell=187874/crash-lightning) is half working

**Current behaviour:**
1.Crash Lightning doesnt enchance your weapon so your Lava Lash or Stormstrike isnt doing aoe damage in front of you

**Expected behaviour:**
1.Hitting 2 or more targets enhances your weapons for 10 sec, causing Stormstrike and Lava Lash to also deal [(24% of Attack power) * ((Attack power + Offhand attack power) * 2 / 3) / Attack power] Nature damage to all targets in front of you.  

**Steps to reproduce the problem:**

1. Use Crash Lightning on target  
2. Step 2
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
