### ISSUE TITLE
Shaman/Talent/Lightning Shield

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#33]
**Description:**
[Lightning Shield](https://www.wowhead.com/spell=192106/lightning-shield) isnt working correctly

**Current behaviour:**
1.Lightning Shield can be stacked by spamming Lightning Shield spell
2.Stormstrike doesnt increase stacks by 2 when used
3.Lightning Shield doesnt stack if you are attacked by enemy

**Expected behaviour:**
1.Lightning Shield should be able to stack with spamming same spell
2.When you Stormstrike, it gains 2 charges.
3.Lightning Shield should get stacks if you get attacked by something
**Steps to reproduce the problem:**

1. Pick Lightning Shield talent(192106)
2. Cast it
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
