### ISSUE TITLE
Shaman/Talent/Totem Mastery(enh)

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#34]
**Description:**
[Totem Mastery(enh)](https://www.wowhead.com/spell=262395/totem-mastery) isnt working at all

**Current behaviour:**
1.Totem Mastery doesnt spawn any totem

**Expected behaviour:**
1.Summons four totems that increase your combat capabilities for 2 min.
**Resonance Totem**
Generates 1 Maelstrom every 1 sec.
**Storm Totem** 
Increases the damage of Stormstrike by 5%.
**Ember Totem**
 Increases Lava Lash damage by 10%.
**Tailwind Totem** 
Increases your chance to trigger Windfury by 2%.

**Steps to reproduce the problem:**

1. Pick Totem Mastery(enh) talent  
2. Use it
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
