### ISSUE TITLE
Shaman/Talent/Searing Assault

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#35]
**Description:**
[Searing Assault](https://www.wowhead.com/spell=192087/searing-assault) isnt working

**Current behaviour:**
1.Flametongue doesnt apply DoT damage when this talent is selected

**Expected behaviour:**
1.Flametongue now causes the target to burn for (54% of Attack power) Fire damage over 6 sec.

**Steps to reproduce the problem:**

1. Pick Searing Assault talent(192087)
2. Cast Flametongue

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
