### ISSUE TITLE
Shaman/Talent/Hailstorm

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#36]
**Description:**
[Hailstorm](https://www.wowhead.com/spell=210853/hailstorm) isnt working

**Current behaviour:**
1.Frostbrand doesnt enchance your weapon

**Expected behaviour:**
1.Frostbrand now also enhances your weapon's damage, causing each of your weapon attacks to also deal (3.159% of Attack power)% Frost damage.

**Steps to reproduce the problem:**

1. Pick Hailstorm talent(210853) 
2. Use Frostbrand on target
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
