### ISSUE TITLE
Shaman/Talent/Fury of Air

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#37]
**Description:**
[Fury of Air](https://www.wowhead.com/spell=197211/fury-of-air) isnt working

**Current behaviour:**
1.When you cast Fury of Air nothing happens

**Expected behaviour:**
1.Creates a vortex of wind 8 yards around you, dealing [(5.25% of Attack power) * ((Attack power + Offhand attack power) * 2 / 3) / Attack power] Nature damage every 1 sec to enemies caught in the storm, and slowing them by 30% for 3 sec.

**Steps to reproduce the problem:**

1. Pick Fury of Air talent(197211) 
2. Cast it

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
