### ISSUE TITLE
Shaman/Talent/Master of the Elements

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#4]
**Description:**
[Master of the elements](https://www.wowhead.com/spell=16166/master-of-the-elements#changelog) doesnt work correctly

**Current behaviour:**
1.Every spell proc it
2.Doesnt increase damage of the next nature or frost spell

**Expected behaviour:**
1.Should be proced only when casting lava burst
2.Should increase damage by 20 % of the next nature or frost spell

**Steps to reproduce the problem:**

1.Pick a Master of the Elements talent(16166)
2. Cast any damaging spell

**Branch(es):**

Master

**TC rev. hash/commit:** 
Dont know

**Operating system:** 
Windows 10

**Comment by searum** [comment]
fix
