### ISSUE TITLE
Mage/Talent/Rune of Power

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#47]
**Description:**
[Rune of Power](https://www.wowhead.com/spell=116011/rune-of-power) is half working

**Current behaviour:**
1.Rune of Power does create circle under you but it doesnt increase spell damage at all.It has just visual effect

**Expected behaviour:**
1.Places a Rune of Power on the ground for 10 sec which increases your spell damage by 40% while you stand within 8 yds.

**Steps to reproduce the problem:**

1. Pick Rune of Power talent(116011)
2. Cast it

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by Keital** [comment]
it works for me
