### ISSUE TITLE
Shaman/Earthquake

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#5]
**Description:**
[Earthquake ](https://www.wowhead.com/spell=61882/earthquake)doesnt work

**Current behaviour:**
1.Earthquake doesnt do damage
2.Earthquake doesnt knock up enemys

**Expected behaviour:**
1.Earthquake should do damage to enemys
2.Earthquake should occasionally proc knock up

**Steps to reproduce the problem:**
1. Cast Earthquake 
2. See if anything happen

**Branch(es):**
Master

**TC rev. hash/commit:** 

**Operating system:**
Windows 10

**Comment by searum** [comment]
Fixed
