### ISSUE TITLE
Scene Cinematics

### ISSUE THREAD

**Issue by xXBentRealityXx** [xXBentRealityXx/Greymane-Bugtracker#56]
**Description:**

The scenes played on first login for allied races either make your cursor disappear or cause a black screen.

**Current behaviour:**

The scenes played on first login for allied races either make your cursor disappear or cause a black screen.

**Expected behaviour:**

These scenes should not cause a black screen or missing mouse cursor.

**Steps to reproduce the problem:**

1. Make an allied race character (Example: Dark Iron Dwarf).
2. Login.

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** Win 10 x64

**Comment by searum** [comment]
Temp fixed
