### ISSUE TITLE
Shaman/Talent/Aftershock

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#6]
**Description:**
[Aftershock ](https://www.wowhead.com/spell=273221/aftershock)doesn't work at all

**Current behaviour:**
1.When you cast Spell(which use maelstrom) it doesnt give maelstrom back
(Tested 20 times on elemental)

**Expected behaviour:**
1.When you cast spell which use maelstrom you have 25 % chance to get maelstrom back

**Steps to reproduce the problem:**

1. Pick Aftershock talent(273221)
2. Cast Spell which use maelstrom

**Branch(es):**
Master

**TC rev. hash/commit:** 
Dont know

**Operating system:**
Windows 10

**Comment by searum** [comment]
Fix
