### ISSUE TITLE
Shaman/Talent/Totem Mastery

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#7]
**Description:**
[Totem Mastery ](https://www.wowhead.com/spell=210643/totem-mastery)doesnt work correctly

**Current behaviour:**
1.Storm Totem doesnt work
2.Other totems work

**Expected behaviour:**
1.Storm Totem should increase your chance of procing Elemental Overload,which seems not to be working

**Steps to reproduce the problem:**

1.Select Totem Mastery talent(210643)  
2. Use Totem Mastery

**Branch(es):**
Master

**TC rev. hash/commit:** 
Dont know

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
