### ISSUE TITLE
Shaman/Talent/Spirit Wolf

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#8]
**Description:**
[Spirit Wolf](https://www.wowhead.com/spell=260878/spirit-wolf) doesnt work

**Current behaviour:**
1.Spirit Wolf doesnt give you buff that gives  you gain 5% increased movement speed and 5% damage reduction every 1 sec, stacking up to 4 times while you are  transformed into a Ghost Wolf

**Expected behaviour:**
1.Spirit Wolf should give you buff that increase movement speed and gives you damage reductin every 1 sec stacking 4 times while in Ghost Wolf

**Steps to reproduce the problem:**
1. Pick Spirit Wolf talent(260878)
2. Use Ghost Wolf

**Branch(es):**
Master

**TC rev. hash/commit:** 
Dont know

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fix
