### ISSUE TITLE
Hunter/Cobra Shot

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#88]
**Description:**
[Cobra Shot](https://www.wowhead.com/spell=193455/cobra-shot) is half working

**Current behaviour:**
1.Cobra Shot do less damage(796 instead of 842(tooltip))
2.Cobra Shot doesnt reduce cooldown of Kill Command by 1 sec

**Expected behaviour:**
1.Requires Ranged WeaponA quick shot causing [(34.5% of Attack power) * ((min(Level - 1, 19) * 12 + 112) / 340)] Physical damage.
2.Reduces the cooldown of Kill Command by 1 sec.

**Steps to reproduce the problem:**

1. Cast Cobra Shot at enemy  
2. Step 2
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
