### ISSUE TITLE
Hunter/Kill Command

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#89]
**Description:**
[Kill Command](https://www.wowhead.com/spell=34026/kill-command) doesnt work

**Current behaviour:**
1.Kill Command does no damage

**Expected behaviour:**
1.Give the command to kill, causing your pet to savagely deal [Attack power * 1.12 * 1 * (0.5 + min(Level, 20) * 0.025) * (1 + Versatility) * 1.06] Physical damage to the enemy.

**Steps to reproduce the problem:**

1. Cast Kill Command on enemy 
2. Step 2
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
