### ISSUE TITLE
Shaman/Talent/Earth Shield

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#9]
**Description:**
[Earth Shield ](https://www.wowhead.com/spell=974/earth-shield)is half working

**Current behaviour:**
1.Earth Shield does give you increased healing by 10 % on that target
2.Earth Shield doesnt heal you when you are attacked

**Expected behaviour:**
1.Earth Shield should heal you when you get attacked by something

**Steps to reproduce the problem:**
1.Pick Earth Shield talent(974) 
2.Pull something to attack you

**Branch(es):**
Master

**TC rev. hash/commit:** 
Dont know

**Operating system:** 
Windows 10

**Comment by searum** [comment]
Fixed
