### ISSUE TITLE
Hunter/Barbed Shot

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#90]
**Description:**
[Barbed Shot](https://www.wowhead.com/spell=217200/barbed-shot) is half working

**Current behaviour:**
1.Barbed Shot bleed is doing less damage than it should(146 instead of 154(tooltip))
2.Barbed Shot doesnt put your pet in frenzy 

**Expected behaviour:**
1.Fire a shot that tears through your enemy, causing them to bleed for [(22.5% of Attack power) * 5] damage over 8 sec.
Sends your pet into a frenzy, increasing attack speed by 30% for 8 sec, stacking up to 3 times.

**Steps to reproduce the problem:**

1. Cast Barbed Shot on enemy 
2. Step 2
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
