### ISSUE TITLE
Hunter/Bestial Wrath

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#91]
**Description:**
[Bestial Wrath](https://www.wowhead.com/spell=19574/bestial-wrath) is half working

**Current behaviour:**
1.Bestial Wrath cooldown remaining isnt reduced by Barbed Shot(12 sec)

**Expected behaviour:**
1.Bestial Wrath's remaining cooldown is reduced by 12 sec each time you use Barbed Shot

**Steps to reproduce the problem:**

1. Cast Bestial Wrath  
2. Cast Barbed Shot
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
