### ISSUE TITLE
Hunter/Exhilaration

### ISSUE THREAD

**Issue by NollBro** [xXBentRealityXx/Greymane-Bugtracker#92]
**Description:**
[Exhilaration](https://www.wowhead.com/spell=109304/exhilaration) is not working correctly

**Current behaviour:**
1.Exhilaration doesnt heal pet,instead all healing is targeted on player(player is healed for 30% and then again for 100% of hp)

**Expected behaviour:**
1.Heals you for 30% and your pet for 100% of maximum health.

**Steps to reproduce the problem:**

1. Cast Exhilaration  
2. Step 2
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

Do not worry about this.

**Operating system:** CHANGEME OS

**Comment by searum** [comment]
Fix
